name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws-auth-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::596234624782:role/GitHubActionsRole
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity
          aws configure list

      - name: Send Slack Notification
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          STATUS: ${{ job.status }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"🚀 *Deployment Status:* $STATUS | *Repo:* $REPO | *Branch:* $BRANCH\"}" \
          "$SLACK_WEBHOOK_URL"
